name: Deploy to Github Pages  # Defines the name of the GitHub Actions workflow.

on:
  push:
    branches:
      - develop  # Triggers the workflow on each push to the 'develop' branch.

jobs:
  build:
    name: Build  # Defines the name of the build job.
    runs-on: ubuntu-latest  # Specifies the operating system for the job.

    steps:
      - name: Checkout Repo  # Checks out the repository.
        uses: actions/checkout@v4

      - name: Create Node Environment  # Sets up Node.js environment.
        uses: actions/setup-node@v4
        with: 
          node-version: 16.x

      - name: Install Packages and Build Application  # Installs npm packages and builds the Vue.js application.
        run: |
          npm ci
          npm run build

      - name: Setup Pages  # Configures pages for deployment.
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll  # Builds the application with Jekyll.
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist/
          destination: ./_site

      - name: Upload artifact  # Uploads the build artifact.
        uses: actions/upload-pages-artifact@v2

  deploy:
    name: Railway Deploy
    needs: build  # Specifies that the deploy job depends on the build job.
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
