name: Deploy to Railway

on:
  push:
    branches:
      - main  # Triggers the workflow on each push to the 'main' branch.

jobs:
  build:
    name: Build  # Defines the name of the build job.
    runs-on: ubuntu-latest  # Specifies the operating system for the job.

    steps:
      - name: Checkout Repo  # Checks out the repository.
        uses: actions/checkout@v4

      - name: Create Node Environment  # Sets up Node.js environment.
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install Packages and Build Application  # Installs npm packages and builds the Vue.js application.
        run: |
          npm ci
          npm run build

  deploy:
    name: Railway Deploy
    needs: build
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
